### ISSUE TITLE
Player Scaling

### ISSUE THREAD

**Issue by ddoubledeuce** [Codes4Fun/RBDOOM-3-BFG#11]
Changing the vr_playerheightcm value seems to scale the player rather than simply change the height.  The result is that the camera rig seems to also get scaled which changes the virtual IPD of the player - making them feel larger (and thus everything else gets smaller) as they get taller, and vice versa as they get shorter.

Also vr_playerheightcm seems to be inverted - smaller numbers make the player larger, and larger numbers make the player smaller. so, a vr_playerheightcm of 500 makes the player very small, and all of the objects in the game seem very large.

**Comment by Codes4Fun** [comment]
I think you may have been trying to compensate for a bug that would push you six inches under the floor. This was fixed in the latest build, and would mean you can set vr_playerHeightCM to your actual height.

But that said, the purpose of vr_playerHeightCM is to scale you to the size of a full size space marine. So for a kid they would feel like an adult. The reason I have that setting is because OpenVR doesn't tell me your actual height.

IPD has to scale with you, it would be bad if your eyes are 3 inches apart, and if you move your head 3 inches that it would instead move 4 inches in the game. It would likely give you motion sickness to decouple those, your head would feel that it is moving more then it should.

Also note this setting is not really intended for seated mode (vr_seated 1), if you want to adjust the height in seated mode you would use vr_resetPose console command instead.

You can kind of disable scaling by lying about your height, and setting your height to the size of a space marine, which is about 194.31
