### ISSUE TITLE
Scale adjustment

### ISSUE THREAD

**Issue by Deapper** [Codes4Fun/RBDOOM-3-BFG#17]
Is there an option to increase scale. I feel the npc are too small, at least their heads are. Great job thx

**Comment by Nagorak** [comment]
I agree with you.  The models in this game are "weird", and I suppose that can't be fixed.  It's funny how that becomes so much more obvious when playing in VR where you can "size up" the models more accurately in relation to yourself.  

But, anyway, their heads are way too small relative to their bodies (or actually their bodies are too big).  They need to be scaled larger, so that they're bulky people with normal sized heads, instead of normal sized people with pin heads.

**Comment by Codes4Fun** [comment]
There was a bug that would put you 6 inches lower, please see if build 7 (latest build) fixes this.

And also use vr_playerHeightCM to set your real world height, and the game should scale you up to the size of everyone else in the game. If it still seems to low, then lie about your height and tell it you are shorter.

**Comment by Codes4Fun** [comment]
The head size also, is the artwork for the game, there is probably a hack I could do to scale them up, I will look into that.

**Comment by Codes4Fun** [comment]
I added a way to increase head scaling (of humans) in the latest build (v8)

Just in the console type:
vr_chibi 1.5
