### ISSUE TITLE
Allow viewpoint height to be set independent of level scaling?

### ISSUE THREAD

**Issue by Nagorak** [Codes4Fun/RBDOOM-3-BFG#20]
Right now the console command that sets the player height actually appears to change the entire scale of the game.  Unfortunately, this doesn't really work right.  If I set the current height (scale) setting, so that the humans have proper proportions, they're also like 7'2" tall because my viewpoint is too low.  If I set the height so that I'm the right height compared to the ground, then the humans are all abnormally small midgets, with tiny heads.  

Being able to set the overall scaling separate from the viewpoint height would solve both of these problems.

**Comment by Codes4Fun** [comment]
> If I set the height so that I'm the right height compared to the ground, then the humans are all abnormally small midgets, with tiny heads.

Could you please provide the console command used to make this happen?

The whole purpose of vr_playerHeightCM is to make you exactly as tall as everyone else. I'd rather fix any bugs with that rather than create two competing settings.

There was a bug fixed in version 7 (released last night), the bug in previous versions would put you 6 inches lower (if you look at chaperon bounds, you would see them below Dooms ground).

**Comment by Nagorak** [comment]
I used the vr_playerHeightCM command.  But the issue is that by scaling you (or actually everything else compared to you) to be as tall as everyone else, the scale gets thrown off.  In real life being taller or shorter only affects how high you see things from.  It doesn't change the overall size that we perceive other people or objects.  

You can see the problem with this by using extreme values of 100 and 300 for height.  At 100, it's not just that your viewpoint is set lower, it's that the room and all of the objects are bigger.  Meanwhile at 300 you're a giant that can walk across the room in 5 steps.  

I guess I see what you're trying to do here, but just scaling things down so a 6'4" (193 cm) marine ends up being 5'10" (178 cm) isn't going to look right.  It's not going to feel like you're 6'4", but rather that everything else is too small.  For my own part, I am actually 6'4".  At that setting (193 cm) the scale of everything looks about right (heads and bodies are the right size), but I'm still too short. I'm only at like shoulder height for most of the human enemies (I guess I could chalk that up to there just being better nutrition in the future).  It's just a weird mismatch that you are aware of in VR that wouldn't be obvious on a monitor.  

I think a better strategy would be to have the game scaled so that everything is proportional to real life, and just have the viewpoint set to be the person's actual height.  So, if you're shorter, you'll be shorter than the other humans, and if you're taller you'll be the same height, or taller than them.  In VR our physical size needs to match how big we really are, or it's obvious something is off.  It's too easy to see that the models are not the right size compared to our experience in real life.  

If you want to make it so that a shorter person feels like they're taller, it would be better to have them "float" a few inches off the ground, because then they'll be physically taller but everything else would still be scaled accurately.  That's really the only difference with being taller-- we're just higher up.

**Comment by Codes4Fun** [comment]
I'm just going to say, outside any perceived size differences you may experience because of scaling, offsetting height would not work for kids or short people because they would not be able to crouch or they would clip through the top of crawl spaces when they did.

You mentioned this yourself in another thread that objects in the world are probably not to scale anyway, which is more of an artwork/asset problem then something I could fix in code alone.

BTW setting your vr_playerHeightCM to 194.31 effectively removes all scaling in the game, you are not that far from that height so there should be very little scaling involved.

And make sure you are running the v7 build as it fixes a bug that makes you 6 inches shorter. When I first developed this I was using an Oculus Rift and didn't notice the height was off, but having got a Vive yesterday I was able to see this issue and fix it.

**Comment by Nagorak** [comment]
Yeah, I think you might be right that the whole scaling of objects is just wonky.  Obviously this wasn't made for VR, so they didn't have to worry about getting everything right.  

It's interesting how perspective is so much more more obvious in VR than in a normal game.
