### ISSUE TITLE
Camera Shaking

### ISSUE THREAD

**Issue by jkostans** [Codes4Fun/RBDOOM-3-BFG#25]
Camera shaking is present in version 7. Elevators, scripted explosions, etc cause it. I thought it was tracking issues at first but turns out the camera is just shaking. Easily recreated using any elevator.

EDIT: I did install the "Doom3 BFG Hi Def" texture pack, could that possibly have re-enabled shaking?

**Comment by asdfffdsa** [comment]
I would like to chime in on this.  On certain levels this camera shaking is present as a periodic effect (every few seconds) rather than being triggered by something.  Basically the whole screen periodically shakes/vibrates on certain levels to create seismic effect.  It's pretty subtle but it's definitely there if you pay attention.  You can also see it in the flat version of the game but it's much more difficult to notice.  I'm sure it's present in many other levels, but it's definitely present in "Mars Underground" immediately following the invasion.

This is basically the one thing that's preventing me from playing for extended periods.

**Comment by Codes4Fun** [comment]
LOL this one was coming from sounds (rumble sound of the elevator, explosive sound from barrels), I have a fix that I will push out in the next release.

I also found it wasn't all explosions, it doesn't do it for grenades/rockets, but those have knockback which can be disabled with "vr_knockbackScale 0".

Thanks for pointing this out BTW.

**Comment by asdfffdsa** [comment]
Hey thanks for looking into this.  Are you certain that this is only triggered by sounds?  It seems to occur regularly--every few seconds in certain levels independent of the player's actions.  Or maybe there is also an environmental sound that's setup to trigger this?  I can't check at the moment--maybe there is such a sound but I didn't think to listen for it

Man, there are definitely a lot of subtle things that affect VR experiences...

**Comment by jkostans** [comment]
Thanks for looking into this. You're  doing amazing work.

**Comment by Codes4Fun** [comment]
It looks like this issue is new and occurs with the OpenAL build, using fallback.exe will allow you to avoid it.

Fallenae (in the Steam community) found this really old thread about people noticing it in Doom3 5 years ago:
http://forums.steampowered.com/forums/archive/index.php/t-2282755.html

**Comment by Codes4Fun** [comment]
I've released a new build that fixes the shaking and you can go back to the OpenAL version with it.
