### ISSUE TITLE
Haptic feedback on vive controllers when weapon fires.

### ISSUE THREAD

**Issue by jlbates** [Codes4Fun/RBDOOM-3-BFG#3]
As a vive user, I'd like some sensory feedback when weapons fire.

**Comment by kickymcassington** [comment]
Agreed that would be awesome and though it's a small effect it really goes a long way to help make the guns feel more real :)

**Comment by Aesop112** [comment]
"Haptic pulse"

**Comment by sc0rch** [comment]
Totally agree, haptic feedback is needed for the immersion.

**Comment by ecaginicolau** [comment]
This is a nice feature request 
+1

**Comment by Codes4Fun** [comment]
Should be working in the latest build.

I have not played enough VR games to know how it should feel, if it doesn't feel right, please provide the name of example game(s) that I can try to replicate and reopen this issue!

**Comment by Strubu** [comment]
First of all thank you for your hard work. It's a really awesome experience. 

Hot Dog, Horseshoes and Hand Grenades is by far the best reference how weapons should feel in VR. 
I think you could improve the feedback quite a bit by making the vibration much stronger (right now its nearly not recognizable) and maybe ever so slightly rotate the weapon upwards around the center of the controller to simulate some feedback (because of this right now pistol e.g. feels more like and airsoft than a pistol).

**Comment by Codes4Fun** [comment]
I've been actually playing around with this a bit, working on intensity and to also have left vibration in some cases, but they are kind of buggy (sometimes tracking stops working :P), so I need to fix those before I release any changes.

OpenVR strangely enough doesn't let you control intensity, rather duration is how you increase intensity, in my last build it would only send one pulse, in my new changes it extends the duration which helps a lot.

I'll check out Hot Dog, Horseshoes and Hand Grenades! Every other game I've tried has been okay, the only difference I can see with them has been in their duration.

**Comment by Codes4Fun** [comment]
I've pushed out a new release that should be a good improvement.
