### ISSUE TITLE
Other games using same engine?

### ISSUE THREAD

**Issue by duig0** [Codes4Fun/RBDOOM-3-BFG#44]
Hiya.....greatest be experience.....ever

What are your thoughts on porting the mod to the likes of....Prey, Rage...original doom 3 etc.

What about later versions of the engine used by Dead island etc....oh the possibilities

**Comment by Kirtaner** [comment]
Rage is not the same engine. Dead Island doesn't use any incarnation of idTech.

**Comment by Codes4Fun** [comment]
The list of games based on idTech 4 can be found here https://en.wikipedia.org/wiki/Id_Tech_4#Games_using_a_proprietary_license

The problem is, most of them are not open source and they likely have done a lot of customization to source code (like Prey adding portals and wall walking, etc). It would take a lot of time to reverse engineer what they have done and reproduce it.

It's possible to do, for example there is someone who forked ioquake3 and reverse engineered Star Trek Elite Forces and added support to ioquake3 that allows people to play Multiplayer Holomatches, but that is only multiplayer, not the single player aspect of the game. https://github.com/thiloschulz/ioef
