### ISSUE TITLE
Window glass becomes opaque

### ISSUE THREAD

**Issue by sdsusnowboards** [Codes4Fun/RBDOOM-3-BFG#45]
EVGA 1080 SC
Intel i7 6700
Window 7
HTC Vive
Doom3 BFG - no mods -Steam edition

I am in Mars City. Some glass windows become opaque and I see specular mapping. I've also had one instance of a steam decal losing its transparency.

Oddly, these issues began happening after a  fresh reinstall of the game, taking care to delete the game folder as well. I was trying this earlier with some HD mods, and I experienced none of these issues.

**Comment by Erare** [comment]
Post processing causes some odd opaque issues with glass and certain fire effects.  The problem isn't always persistent but in certain areas of the game it can be pretty bad.

r_skippostprocess 1 to turn off the warbly glass and fire effects and fix this problem.

**Comment by Codes4Fun** [comment]
technically that is not a fix, just a work around.

out of curiousity what was the texture pack?

**Comment by Erare** [comment]
I've experienced the issue with just plain old vanilla Doom3BFG.

**Comment by Codes4Fun** [comment]
Had you used any texture packs before?

On Dec 3, 2016 9:17 PM, "Erare" <notifications@github.com> wrote:

I've experienced the issue with just plain old vanilla Doom3BFG.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Codes4Fun/RBDOOM-3-BFG/issues/45#issuecomment-264685112>,
or mute the thread

**Comment by sdsusnowboards** [comment]
Hi Codes, I was using the following mods.
highres_textures_d3_v14_full
new_shaders_pack_v20_full_mod_for_d3_27112k8
d3_parallax ("Parallax Extreme," I think)

The game crashed while loading alpha, so I delete all local content, including folders, and started fresh.

Erar,

Thanks! I'll try that tomorrow and see how it works. I wasn't digging the window distortion in VR anyway, so it's not much of a loss.

**Comment by Erare** [comment]
Yes I've uninstalled and reinstalled Doom 3 several times in the last couple of weeks and tried out a few different texture packs in between.

However I am 100% certain that I have seen the blue sprites after a clean install.  Next time I play, I will do a clean wipe and I will also clear out the steamapps doom 3 BFG folder before downloading, and see If I can get the sprites to appear, to confirm.

**Comment by Erare** [comment]
I did a clean wipe and played on game/hell1.  I didn't get blue sprites but instead I still got strange opaque sprites in place of the distortion effects.  Their appearance was a lot like noclipping in the original doom.

**Comment by Codes4Fun** [comment]
I don't mind people using work arounds, but I just wanted info so that I can attempt to reproduce this issue (I actually have the same specs as sdsusnowboards). Fixing it or at least understanding it better would benefit my end goal of creating a game from this engine.

You might have deleted everything in doom 3 folders, but video card drivers themselves do caching (to improve performance) and that could have been corrupted by trying to use another mods data and then switching back.

**Comment by Codes4Fun** [comment]
BTW here is some info on the shader cache: http://www.overclock.net/t/1553142/shader-cache-setting If you ever have wanted to clear out your shader cache, you would need to disable it in the NVidia control panel (under Manage 3D settings), then restart the computer and delete the folder %USERPROFILE%\AppData\Local\Temp\NVIDIA Corporation\NV_Cache

You don't have to do this, I will try and reproduce the issue and see if this will fix it.

**Comment by sdsusnowboards** [comment]
I did a clean reinstall of NVIDIA drivers, per your suggestion. The problem persists. I took a video of it happening in the Infirmary in Mars City. It doesn't occur with all windows. Position matters. I could move a few feet to the side and the window will then function fine. 

https://youtu.be/V0g4Nf5CZnw

I will disable the shader cache, delete the cache, then update this post. 
Update: Deleting the shader cache did not resolve the issue.

I can confirm that r_skippostprocess 1 does resolve the issue in the Infirmary. 

I just now noticed the following language in my console,
***warnings***
during game/mars_city2...
WARNING: Couldn't load image: _emptyname : _emptyname*__0200
WARNING: Couldn't load image: } : }#__0200

**Comment by Codes4Fun** [comment]
Actually, I can reproduce the issue with MSAAx8, so it is definitely not to do with shaders. In fact I think this is what Samson (the other mod maker) was telling me about, I'm going to investigate this more and try out his fix.

**Comment by Codes4Fun** [comment]
An alternative way to resolve it is to use "r_useScissor 0" and you can keep the warping effects.

But I'm still investigating why it happens. It appears that some optimization they do with scissors doesn't work with MSAAx8.

**Comment by sdsusnowboards** [comment]
Excellent. I will use that command.

FYI: I am using MSAAx2.

I'd be using vr_resolutionscale, but any value over 1 causes crazy judder and/or Doom 3 to become unresponsive.

**Comment by Codes4Fun** [comment]
This was so simple I felt stupid I didn't look at this first. So it turns out that something prior to post processing was setting a scissor to be really small, and glBlitFramebuffer (used for MSAA) respects the scissor test, so it wasn't copying the entire image before doing warps. I found several other places this can occur and fixed those also. This is why this issue is random (I couldn't reproduce it), something has to be drawn before post processing that leaves a small scissor region, possibly particle effects behind or in front of windows.

And Samson essential did the same fix when [he came across this problem](https://forums.oculus.com/community/discussion/comment/457181/#Comment_457181), but he thought it was the graphics driver (it wasn't!) and he doesn't restore the state of the scissor afterwards so he may potentially be missing out on scissor optimizations and maybe some other bugs but then  again maybe not, it is not entirely clear to me why it is uses scissors in the first place.

Thanks for the help on this issue guys!

**Comment by Erare** [comment]
Dang, you programmers are on another level than us gaming enthusiasts.  Thanks for your persistence on these issues, it's a true gift to the VR community!

**Comment by sdsusnowboards** [comment]
Outstanding! Thank you for your attention to the issue.

VR Doom is almost too terrifying to play, but I keep coming back for some reason.
