### ISSUE TITLE
How can I reference Vive controller mappings in cfgs?

### ISSUE THREAD

**Issue by poseyjmac** [Codes4Fun/RBDOOM-3-BFG#46]
Since I can't find a way to make pm_ variable changes stick from level to level yet, I'd like to just bind 'exec autoexec.cfg' to a button that's not in use. Also binding 'give all' to a button would be nice as well.

**Comment by Codes4Fun** [comment]
> Since I can't find a way to make pm_ variable changes stick from level to level yet

Just do this, in the console type this:
extractResourceFile _common.resources temp

This will extract some game data to a new folder called "temp". In your "base" folder, create a new folder called "def", and copy "temp/def/player.def" to your new "base/def" folder. From there open "base/def/player.def" in your favorite editor and you should find all the pm_ variables that get wiped on level loading, since it is this file that is overriding what you set from console and cfg, and the game should use the extracted version first before reading it from _common.resources.

> Also binding 'give all' to a button would be nice as well.

I'm not sure if it is possible to do that, but all buttons are being passed as their gamepad equivalents, if you rebind the ones for the gamepad it will rebind them for the motion controllers.

For example left trigger is mapped to JOY1 which is bound to jump in the cfg:
bind "JOY1" "_moveup"

But this is far from perfect, and this is probably going to change in future versions.

**Comment by poseyjmac** [comment]
Very cool, that'll work, thanks!
