### ISSUE TITLE
Constructive feedback on movement settings.

### ISSUE THREAD

**Issue by ghost** [Codes4Fun/RBDOOM-3-BFG#50]
Okay, first of all, holy fucking balls, **wow.** Just, I'm gonna get vulgar here, jesus fucking apeshit christ, you just made this $868 worth every one of 86,800 pennies. It would be one thing to get it working in stereo, but you blew my mind with the (apparently manually done) camera handling for cut-scenes. 

I realize at this point this project is starting to reach that stage where the sheer number of requests surrounding it becomes annoying, but damn, you did a great job. This isn't a specific request, but just my thoughts and experience.

So when I first started I had a lot of difficulty figuring out what was going on with the controls. Forward made me move forward but not all the time. I figured out it was based on the controller's vector, naturally.

I think the problem with this is slight deviation that results in constant slight strafing. I was running into walls like a n00b- sideswiping them.

I think the best way to do this MAY be to do what you're already doing, but use the toucanpad as if it were a d-pad. Allow the player to move forward and back and strafe - cardinal directions only, and control what direction the player moves in based on the direction of the HMD. This will always produce a consistent response %100 of the time, while still allowing for strafing. The downside is that now you have to change the angle of your head to determine the forward direction. This works very well in Windlands, the first game I played that I felt was a "full game" experience.

This is a 16-tries tough topic, I know because I spent several months tinkering with motion controls in a Unity project. I'm going to give your different settings some more time. Like I said earlier, it's no specific request or report, just feedback and fanmail. 

Again, what the fuck sir, you adapted the cutscenes fully???? Are you secretly John Carmack disappointed that you chose the wrong HMD to program on?

**Comment by Razgoggles** [comment]
I just made a branch with a hmd based movement option because I thought it would make sense as an FPS. Fair warning  - it made me a bit dizzy to move like that especially when my feet weren't lined up with my head.    

I think the trick to using the controller based movement is not to think of it as "forward" or "backward" like a traditional controller but "that way". Because no matter how the controller or your head is oriented "that way" on the track pad means "that way" in space.

**Comment by Codes4Fun** [comment]
Thanks Razgogles, I've been meaning to add several options for movement direction,  like the right controller (which lefties would like), but also some combination of the left and right hands to predict the facing of the body and use that as a direction.

**Comment by Codes4Fun** [comment]
I think you may have also been dizzy because of a bug. You can more easily see it if you get near your chaperone bounds so they are visible and physically move near them, the bounds will move differently than the ground does in the game.

Basically I was doing the same calculation twice, and you modified the one that determines what controller input does but not the one that determines what real world movement does. So I consolidated that into one place, instead of doing the calculation twice (something that I should have done in the first place). I also added support for using the right controller to determine the forward move direction.

**Comment by Razgoggles** [comment]
You're right. The trackpad movement actually worked as intended if I stood still, but moving my head caused extra in-game motion. Serves me right for writing one line of code and calling it a day.

**Comment by ghost** [comment]
Man guys, I'm not talented enough to contribute to this project, but
seriously this is awesome. Thanks so much again. I got a 50 ft active HDMI
and USB-over-ethernet and things are gonna get REAL weird today!
