### ISSUE TITLE
Suggestion for aiming/view control with controller/keyboard+mouse

### ISSUE THREAD

**Issue by X3roxx** [Codes4Fun/RBDOOM-3-BFG#60]
Can you maybe implement a freeaim mode like Arma2 has it for a seperation between the headmovement and the aiming. You have it already for the y-axis but for the x-axis it's really weird if you move the weapon and the view sticks to the weapon movement. I think it's fine if the weapon starts to turn if you reach the border of the FOV.

**Comment by Codes4Fun** [comment]
I am still investigating the best way to do this, the funny thing is that Doom 3 has something that is complete opposite of this, in that the weapon is lagged from view turning.

**Comment by X3roxx** [comment]
So you mean the weapon "slowly" follows the head movement? I'm playing around a bit at the moment to find the best adjustments and setting for my setup.  Doom is very nice and immersive with a wiimote but unfortunately it don't support 360 tracking so the HMD- Controller are always asynchronus while gaming

**Comment by Codes4Fun** [comment]
Yup

**Comment by Codes4Fun** [comment]
I added it to the release page as 12.3

It is intended for seated play (vr_seated 1), since it is a keyboard and mouse thing.

vr_turnSlack 27

...was a good number in my tests but you might want to use less than that depending on your FOV.

**Comment by X3roxx** [comment]
yeah, this is completely different to play now! Thank you!! Anyways there is still  a problem with the synchronization so i want to ask you if it is poosible to make another option similar to  "vr_resetpose" but recentering to the current direction of view instead of the current body direction.

**Comment by Codes4Fun** [comment]
I'm guessing you mean you want a way to recenter the weapon to the view, or did you mean something else?

**Comment by X3roxx** [comment]
yes, exactly:-)

**Comment by Codes4Fun** [comment]
okay

**Comment by Codes4Fun** [comment]
I have implemented something but I wanted to double check it is what you had in mind. I have created an action called "_recenter" and it can be bound to a button, like mouse button 2:

bind "MOUSE2" "_recenter"

And when pressing mouse button two it will recenter the weapon (towards the seated position forward), if you hold the button and move the mouse it behaves like it used to (equivalent to "vr_turnSlack 0") and when you release the button, it will then allow the gun to move within range set by vr_turnSlack.

**Comment by X3roxx** [comment]
Cool, thanks! Sounds like what i have in mind. Btw. i made a keybind for the vr_resetpose as well to make it more comfortable.

I will try it out then and let you know how it works

**Comment by Codes4Fun** [comment]
I updated the release with "_recenter", version 12.4:

https://github.com/Codes4Fun/RBDOOM-3-BFG/releases/tag/1.1.0-openvr12

You can toss this at the bottom of your cfg or in the console if you want to use it with the right mouse button for example:

bind "MOUSE2" "_recenter"

> Btw. i made a keybind for the vr_resetpose as well to make it more comfortable.

You shouldn't need to make a binding for that, it uses a low level [SteamVR system call](https://github.com/ValveSoftware/openvr/wiki/IVRSystem::ResetSeatedZeroPose), it should be a one time thing, and only if you have never told steam what your seated pose is or need to update steam about your seated pose, because this effects every other seated game.

There is a known bug with it, if you don't have SteamVR started before the game, but there are several other bugs associated with doing that (for me it lacks sterescopic 3d). I think SteamVR fixes this in their beta version.

**Comment by X3roxx** [comment]
Just made a short test..unfortunately it's not what i was looking for as i would need the weapon recentered to my current direction of view as I'm standing and turning around my whole body 360°

**Comment by Codes4Fun** [comment]
okay, it sounds like you are trying to use current modes of play, to play in a way they were not intended (it makes sense why you were trying to use vr_resetPose now). Seated mode is limited to 180. The title of this issue mentions mouse+keyboard, for most of us out there, we can't do 360 mode of play with mouse and keyboard.

I'm closing this issue. I suggest reopening a new one and describe how you want to control the game and not how I should modify existing modes of play (which you might be using incorrectly because they can be hacked to be close to what you want). For example, are you even sitting, or are just using seated mode because it has vr_resetPose?
