### ISSUE TITLE
Won't display in Vive - SteamVR shows (unresponsive) RBDoom3BFG.exe  

### ISSUE THREAD

**Issue by fosterman** [Codes4Fun/RBDOOM-3-BFG#66]
Not sure what I'm doing wrong here - followed the directions. I can see everything is running and the headset is tracking via the desktop display, but it's not showing anything in the Vive and SteamVR shows the (unresponsive) RBDOOM3BFG.exe message as soon as I launch. Is there anything I can try?

**Comment by Codes4Fun** [comment]
What is your hardware setup? Does it have embedded graphics (like in a laptop for example)? One issue I've seen people have is that Nvidia control panel can direct applications to use intel's gpu instead of its own GPU, and they fix it by going into the control panel and making sure rbdoom3bfg.exe is using the Nvidia GPU:

http://www.howtogeek.com/175281/how-to-force-graphics-options-in-pc-games-with-nvidia-amd-or-intel-graphics/

**Comment by fosterman** [comment]
Thanks very much, that was exactly the problem. Thanks for all your work!
